version: "2"

networks:
  treez-net:
    driver: bridge

volumes:
  treez-psql-volume:
    driver: local

services:
  psql:
    restart: unless-stopped
    image: postgres:12.1-alpine
    container_name: psql
    ports:
      - "5432:5432"
    networks:
      - treez-net
    environment: 
      - POSTGRES_DB=treez_api_test
      - POSTGRES_USER=treez
      - POSTGRES_PASSWORD=password
    logging:
      options:
        max-size: 1m
        max-file: "5"
    volumes:
      - treez-psql-volume:/var/lib/postgresql/data
  
  api:
    build: .
    container_name: api
    ports:
      - "1337:1337"
    networks:
      - treez-net